# Generated by Django 2.2.5 on 2019-09-17 17:22

import apps.base.models.usercustom
import apps.base.rename_image
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last login')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, verbose_name='Super Admin')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='User name')),
                ('first_name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('email', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Phone')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=255, null=True, verbose_name='Sex')),
                ('avatar', models.ImageField(blank=True, default='avatar/default_avatar.png', max_length=255, null=True, storage=apps.base.rename_image.RenameImage(), upload_to=apps.base.models.usercustom.image_path)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
